title: SnickerBuzz - Variety Within
email: saquib.ahmad9898@gmail.com
name: SnickerBuzz
description: SnickerBuzz gets you to know about Celebrity, the latest Celebrity News and Celebrity Gossip and various Blogs to read, movies to download and watch them at ease.
markdown: kramdown
thumbnail: "images/logo.png"
author: Syed Saquib Ahmad
excerpt_separator: "<!--more-->"
enforce_ssl: snickerbuzz.com
plugins:
  - jekyll-feed